---
title: |
  | Practical Machine Learning Course Project
  | Weightlifting Exercises Classification
author: "Andrew Thorsen"
date: "April 10, 2016"
output: html_document
---

## Executive Summary

```{r,message=FALSE,warning=FALSE}
library(caret)
library(randomForest)
```

```{r,cache=TRUE}
trainingOriginal <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv")
validationOriginal <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv")
training <- trainingOriginal
validation <- validationOriginal
training <- training[,colSums(is.na(training))==0]
training <- training[,colSums(training=="")==0]
training <- training[,c(8:60)]
validation <- validation[,c(which(names(validation)%in%names(training)),dim(validation)[2])]
##names(training)
##names(validation)
```

```{r,cache=TRUE}
inTrain <- createDataPartition(y=training$classe,p=.5,list=FALSE)
train <- training[inTrain,]
test <- training[-inTrain,]
dim(train)
dim(test)
modFit <- train(classe~.,data=train,method="rf",prox=TRUE)
modFit$finalModel
```


